version: '3.8'

services:

  spark:
    container_name: spark
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: "2g"
    image: veribilimiokulu/pyspark-3.4.1_python-3.8:1.0
    ports:
      - "8888:8888"
      - "4041:4040"
    networks:
      - vbo
    volumes:
      - ./spark/examples:/opt/examples
    command: sleep infinity

  kafka:
    container_name: kafka
    image: erkansirin78/kafka:3.2.0
    build:
      context: ./kafka
    ports:
      - "9092:9092"
      - "9091:9091"
    networks:
      - vbo
    volumes:
      - ./kafka/config/server.properties:/kafka/config/server.properties

  
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: es
    environment:
      - node.name=es
      - cluster.name=es-docker-single
      - discovery.seed_hosts=es
      - cluster.initial_master_nodes=es
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - vbo

  kib:
    image: docker.elastic.co/kibana/kibana:7.17.0
    depends_on:
      - es
    container_name: kib
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es:9200
      ELASTICSEARCH_HOSTS: http://es:9200
    networks:
      - vbo

volumes:
  data:
    driver: local

networks:
  vbo:
    driver: bridge